version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: user_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userStorage_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: user_app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - ENV=docker
      - DB_HOST=postgres
    volumes:
      - .:/app
    networks:
      - user_network

volumes:
  postgres_data:

networks:
  user_network: