database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "userStorage_db"
  sslmode: "disable"

logger:
  level: "debug"   # или "info", "warn", "error"
  encoding: "json"  # или "console" (для разработки)
  output_paths: ["stdout", "logs/app.log"]  # Куда писать логи
